// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKd_o0FJcS5esFcwTBM5YxPW-IXBFM4sQ',
    appId: '1:1019619641680:web:c139ec3eb4d5bed5428455',
    messagingSenderId: '1019619641680',
    projectId: 'chatapptute-103d9',
    authDomain: 'chatapptute-103d9.firebaseapp.com',
    storageBucket: 'chatapptute-103d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7a7rY-zqSENlxAzRk4QEwaZxJBzKgy1c',
    appId: '1:1019619641680:android:a93413c79e55cf50428455',
    messagingSenderId: '1019619641680',
    projectId: 'chatapptute-103d9',
    storageBucket: 'chatapptute-103d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAketkxlsnSxEOygCRLMWNaTL7PnNKpjX0',
    appId: '1:1019619641680:ios:a392f2555e213def428455',
    messagingSenderId: '1019619641680',
    projectId: 'chatapptute-103d9',
    storageBucket: 'chatapptute-103d9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAketkxlsnSxEOygCRLMWNaTL7PnNKpjX0',
    appId: '1:1019619641680:ios:35fedce7781ecb0c428455',
    messagingSenderId: '1019619641680',
    projectId: 'chatapptute-103d9',
    storageBucket: 'chatapptute-103d9.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
